### ISSUE TITLE
[自荐][开源] 利用Github Actions 自动识别翻译非英文issue内容

### ISSUE THREAD

**Issue by tomsun28** [ruanyf/weekly#1678]
- 项目描述： 这是一个使用github action制作的自动识别翻译非英文issue内容的机器人项目。

- action 市场地址: https://github.com/marketplace/actions/issues-translator      
- github 地址: https://github.com/tomsun28/issues-translate-action     

- 示例代码：

````
name: 'issue-translator'
on: 
  issue_comment: 
    types: [created]
  issues: 
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tomsun28/issues-translate-action@v2.3
````

- 截图：   
![效果](https://raw.githubusercontent.com/tomsun28/issues-translate-action/main/dist/bot-demo.png)
