### ISSUE TITLE
【开源自荐】Denoflow - 简单、强大、无服务器的自动化工作流工具，基于yaml配置文件和Deno

### ISSUE THREAD

**Issue by theowenyoung** [ruanyf/weekly#2176]
[Denoflow](https://github.com/denoflow/denoflow)是一个简单、强大、无服务器的自动化工作流工具，基于[`yaml`](https://yaml.org/)配置文件和[Deno](https://deno.land/)，你可以使用任何Deno模块、Typescript/Javascript代码来运行你的工作流。Denoflow会按照你的要求执行你的工作流程。

项目地址： <https://github.com/denoflow/denoflow>
在线体验：通过[Online Playground](https://playground.owenyoung.com)在线尝试和探索 Denoflow

简体中文文档: <https://github.com/denoflow/denoflow/blob/main/README-ZH.md>

能做什么:

- 比如做一个Github Webhook来在服务器同步部署最新代码
- 比如监听RSS的更新，发送到Telegram或者Discord等
- 以及其他一切可以通过API互相调用的流程

一个典型的工作流配置文件长这样：

```yaml
sources:
  - from: https://deno.land/x/axiod@0.24/mod.ts
    use: get
    args:
      - https://test.owenyoung.com/slim.json
    itemsPath: data.hits
    key: objectID
    limit: 1
steps: 
  - run: console.log('item', ctx.item)
  # Open: <https://requestbin.com/r/enyvb91j5zjv9/23eNPamD4DK4YK1rfEB1FAQOKIj> , See live webhook request.
  - from: https://deno.land/x/axiod@0.24/mod.ts
    use: post
    args:
      - https://enyvb91j5zjv9.x.pipedream.net/
      -  ${{ctx.item}}
      - headers:
          'Content-Type': 'application/json'
```

多谢阮老师提供的平台，已经在这里推出过4个项目了！
