### ISSUE TITLE
【开源自荐】Auto Machine，一键安装的AI智能助手

### ISSUE THREAD

**Issue by waht41** [ruanyf/weekly#6391]
地址 https://github.com/waht41/auto_machine 欢迎使用
# demo展示
![Image](https://github.com/user-attachments/assets/4f5e6ee9-59f6-47a1-8fec-c6c71a0b6cd0)

# auto machine是什么？

1. auto machine是一个桌面软件，基于roo code，用于让AI自动化的完成一些任务。

2. auto machine使用yaml作为人与AI的桥梁，通过在yaml文件中配置AI能够使用那些文件，让AI根据用户指定的task自行决定如何规划任务。具体流程如下

   1. 首先，AI读取预先写好的auto machine prompt，内包含软件说明，以及tool使用教程，例如

      ```yaml
      tool: browser
      keyword: "hello world"
      cmd: search
      engine: "bing"
      ```

   3. AI认为需要调用tool时，会使用yaml书写对应的tool工具，后台worker会解析yaml为对应的命令，然后执行预先写好的命令。命令执行结束后，会返回命令的结果，并输入给AI
   4. AI根据结果判断是否继续操作

3. auto machine技术上使用react前端，electron中间层，node worker处理后台逻辑，通过api接口与大模型提供方进行对话。

# Auto Machine有什么优势？

**一键安装:**
相较于auto gpt，open manus之类的基于python实现的AI代理，auto machine不需要额外配置诸多额外环境

**节省token：**
auto machine采用按需采取prompt的方式，不会一次加载所有预设信息，这会显著节约花费。

**开源免费**
用户可自由使用api key和大模型对话，无需第三方介入。 欢迎下载并提出改进意见
