### ISSUE TITLE
lint-md

### ISSUE THREAD

**Issue by hustcc** [ruanyf/weekly#98]
> 用于检查中文 markdown 编写格式规范的命令行工具，基于 AST 开发，且方便扩展和集成 ci。

地址：[lint-md](https://github.com/hustcc/lint-md)

```bash
Usage: <lint-md> <files...> [options]

lint your markdown files

Options:
  -v, --version                  output the version number
  -c, --config [configure-file]  use the configure file, default .lintmdrc
  -h, --help      
```

----

也推荐在这个 weekly 中用起来！

 - Travis

在 .travis.yml 文件中配置以下内容。

```yml
language: node_js
node_js:
  - "10"
before_install:
  - npm i -g lint-md
script: lint-md ./doc
```
